version: "3"

services:
 db:
    image: postgres:10
    environment:
      - POSTGRES_DB:  postgres
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    volumes:
      - db-data: /var/lib/postgresql/data
    web:
      build: .
      command: bash -c
      volumes:
      - .:/code
      ports:
      - "8080:8080"
      depends_on:
       -db
    command: nodemon index.py
volumes:
  db-data:
     driver: local 